[package]
name = "lsf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.12", features = ["derive"] }
chrono = "0.4.19"
crossterm = "0.23.2"
libc = "0.2.125"

